replicaCount: 1

image:
  repository: ghcr.io/akhfa/go-fail
  pullPolicy: IfNotPresent
  tag: "main"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

config:
  startupTime: 20
  timeBeforeExit: 0
  exitCode: 0
  port: 8080

resources:
  limits:
    cpu: 5m
    memory: 5Mi
  requests:
    cpu: 5m
    memory: 5Mi

nodeSelector: {}

tolerations: []

affinity: {}
